export const devicesInitialState: DevicesState = {
  state: [
    {
      id: 1,
      name: "alvo 11",
      imei: 123123123,
      activation_date: Date.now(),
      last_update: Date.now(),
      model: "A30",
      sim_operator1: "claro",
      sim_operator2: "oi",
      connection_type: "Wifi",
      ssid: "teste 01",
      baterry_level: 88,
      ram_level: 72,
      internal_storage_level: 56,
      android_version: "10.0",
      apk_version: "2.0",
      status_chat_service: 1,
      status_extras_service: 1,
      status_admin: 0,
      notification_off: 1,
      camera: 0,
      contacts: 1,
      location: 1,
      mic: 1,
      storage: 1,
      telephone: 1,
      calls: 1,
      sms: 1,
      reg_id: "ab01",
    },
    {
      id: 2,
      name: "alvo 90",
      imei: 123123123,
      activation_date: Date.now(),
      last_update: Date.now(),
      model: "S20",
      sim_operator1: "vivo",
      sim_operator2: "tim",
      connection_type: "4G+",
      ssid: "claro",
      baterry_level: 29,
      ram_level: 88,
      internal_storage_level: 69,
      android_version: "9.0",
      apk_version: "2.0",
      status_chat_service: 0,
      status_extras_service: 0,
      status_admin: 1,
      notification_off: 0,
      camera: 1,
      contacts: 1,
      location: 1,
      mic: 1,
      storage: 1,
      telephone: 1,
      calls: 1,
      sms: 1,
      reg_id: "ab02",
    },
  ],
};
