export const whatsappInitialState: WhatsappState = {
    state: [
    {
      name:"Júlia",
      conversation:[ {
        id: 1,
        date_time:Date.now(),
        contact_name:"Júlia",
        contact_group:"",
        direction:0,
        type:1,
        message_type:1,
        message:"Oi Júlia",
        mention_type:0,
        mention_contact:"",
        mention_message:"",
        read:0,
      },
      {
        id: 2,
        date_time:Date.now(),
        contact_name:"Júlia",
        contact_group:"",
        direction:0,
        type:1,
        message_type:2,
        message:"Quanto tempo, tu sumiu",
        mention_type:0,
        mention_contact:"",
        mention_message:"",
        read:0,
      },
      {
        id: 3,
        date_time:Date.now(),
        contact_name:"Júlia",
        contact_group:"",
        direction:1,
        type:2,
        message_type:1,
        message:"oie, tu que sumiu kkk",
        mention_type:1,
        mention_contact:"Você",
        mention_message:"Quanto tempo, tu sumiu",
        read:0,
      },
    ]
    },
    {
      name:"Política Ibirapitanga",
      conversation:[ {
        id: 4,
        date_time:Date.now(),
        contact_name:"Política Ibirapitanga",
        contact_group:"",
        direction:0,
        type:1,
        message_type:1,
        message:"Agora é Jé 11",
        mention_type:0,
        mention_contact:"",
        mention_message:"",
        read:0,
      },
      {
        id: 5,
        date_time:Date.now(),
        contact_name:"Política Ibirapitanga",
        contact_group:"Dudu",
        direction:1,
        type:3,
        message_type:3,
        message:"e Dr. Junior pra vereador",
        mention_type:0,
        mention_contact:"",
        mention_message:"",
        read:0,
      },
      {
        id: 6,
        date_time:Date.now(),
        contact_name:"Política Ibirapitanga",
        contact_group:"Justin Lanza",
        direction:1,
        type:4,
        message_type:1,
        message:"que nada é Heberte vereador e Junilson prefeito",
        mention_type:1,
        mention_contact:"Dudu",
        mention_message:"e Dr. Junior pra vereador",
        read:0,
      },]
    },
    ],
  };
  